CBI-1610 -- NFT client
Cerebellum-Network/cere-ddc-sdk-kotlin pull request #2
Opened 2021-12-20 15:34 UTC by svalasovich

2021-12-21 00:56 UTC, spoluyan commented on core/src/main/kotlin/network/cere/ddc/core/extension/String.kt
> +fun String.hexToBytes(): ByteArray = Hex.decode(this.removePrefix(HEX_PREFIX))
Use KHex extensions since you have it as a dependency.

2021-12-21 00:56 UTC, spoluyan commented on core/src/main/kotlin/network/cere/ddc/core/extension/String.kt
> +fun ByteArray.toHex(withPrefix: Boolean = true): String {
Same as above

2021-12-21 00:56 UTC, spoluyan commented on core/src/main/kotlin/network/cere/ddc/core/extension/String.kt
> +fun ByteArray.sha256(): String {
Use extensions from https://github.com/komputing/KHash

2021-12-21 00:56 UTC, spoluyan commented on buildSrc/src/main/kotlin/Versions.kt
> +    val kotlin = "1.5.10"
Use 1.5.31

2021-12-21 00:56 UTC, spoluyan commented on build.gradle.kts
> +            "testImplementation"("org.assertj:assertj-core:${Versions.assertj}")
Use `io.kotest:kotest-assertions-core-jvm:5.0.1` for Kotlin-style assertions

2021-12-21 00:56 UTC, spoluyan commented on build.gradle.kts
> +            "testImplementation"("com.github.tomakehurst:wiremock:${Versions.wiremock}")
Why do you need it?

2021-12-21 00:56 UTC, spoluyan commented on core/src/main/kotlin/network/cere/ddc/core/exception/DdcException.kt
> +open class DdcException(message: String?, cause: Throwable?) : RuntimeException(message, cause) {
Use default parameters (nulls) to generate all possible constructors automatically

2021-12-21 00:56 UTC, spoluyan commented on core/src/main/kotlin/network/cere/ddc/core/signature/Ed25519.kt
> +class Ed25519(privateKey: String) : Scheme {
Use proper names for variables.
`privateKeyHex` for constructor
`privateKey` and `publicKey` for byte arrays
`privateKeyHex` and `publicKeyHex` for hex strings

2021-12-21 00:56 UTC, spoluyan commented on core/src/main/kotlin/network/cere/ddc/core/signature/Ethereum.kt
> +    private val pair: ECKeyPair
Better name is `keyPair`

2021-12-21 00:56 UTC, spoluyan commented on core/src/main/kotlin/network/cere/ddc/core/signature/Scheme.kt
> +        const val ETHEREUM = "ethereum"
Use `secp256k1` because it's not limited to Ethereum. Also rename implementation classes.

2021-12-21 00:56 UTC, spoluyan commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/NftStorage.kt
> +        runBlocking { client.storeAsset(nftId, data, name) }
Do not block

2021-12-21 00:56 UTC, spoluyan commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/NftStorage.kt
> +        runBlocking { client.readAsset(nftId, nftPath) }
Do not block

2021-12-21 00:56 UTC, spoluyan commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/NftStorage.kt
> +        runBlocking { client.storeMetadata(nftId, metadata) }
Do not block

2021-12-21 00:56 UTC, spoluyan commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/NftStorage.kt
> +        runBlocking { client.readMetadata(nftId, nftPath, schema) }
Do not block

2021-12-21 00:56 UTC, spoluyan commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/NftStorageAsync.kt
> +class NftStorageAsync(private val client: TransportClient) {
Use suspend functions to void Future wrappers and global scope.

2021-12-21 00:56 UTC, spoluyan commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/client/HttpTransportClient.kt
> +    private val objectMapper = jacksonObjectMapper()
Jackson object mapper may block your thread. You can't avoid it just by using `@Suppress`

2021-12-21 00:56 UTC, spoluyan commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/client/HttpTransportClient.kt
> +    private val nodeFlag = AtomicInteger()
What's the purpose of this variable?

2021-12-21 00:56 UTC, spoluyan commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/client/TransportClient.kt
> +interface TransportClient: Closeable {
Make it `AutoCloseable`

2021-12-21 00:56 UTC, spoluyan commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/exception/NftException.kt
> +open class NftException(message: String?, cause: Throwable?) : DdcException(message, cause) {
Use default parameters (nulls) to generate all possible constructors automatically

2021-12-21 08:01 UTC, svalasovich commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/exception/NftException.kt
> +open class NftException(message: String?, cause: Throwable?) : DdcException(message, cause) {
Updated

2021-12-21 08:01 UTC, svalasovich commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/client/TransportClient.kt
> +interface TransportClient: Closeable {
Updated

2021-12-21 08:08 UTC, svalasovich commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/client/HttpTransportClient.kt
> +    private val nodeFlag = AtomicInteger()
It's simple flag for implementing Round-robin client side balancing

2021-12-21 08:10 UTC, svalasovich commented on buildSrc/src/main/kotlin/Versions.kt
> +    val kotlin = "1.5.10"
Updated

2021-12-21 08:11 UTC, svalasovich commented on build.gradle.kts
> +            "testImplementation"("com.github.tomakehurst:wiremock:${Versions.wiremock}")
It's for unit tests HTTP Transport Client without real DDC Nodes. `HttpTransportClientTest`

2021-12-21 08:12 UTC, svalasovich commented on core/src/main/kotlin/network/cere/ddc/core/exception/DdcException.kt
> +open class DdcException(message: String?, cause: Throwable?) : RuntimeException(message, cause) {
Updated

2021-12-21 08:16 UTC, svalasovich commented on core/src/main/kotlin/network/cere/ddc/core/signature/Ed25519.kt
> +class Ed25519(privateKey: String) : Scheme {
Updated

2021-12-21 08:16 UTC, svalasovich commented on core/src/main/kotlin/network/cere/ddc/core/signature/Ethereum.kt
> +    private val pair: ECKeyPair
Updated

2021-12-21 08:32 UTC, svalasovich commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/NftStorageAsync.kt
> +class NftStorageAsync(private val client: TransportClient) {
If we add suspend, It will be totally Kotlin library. I suggest right now create class NftStorage for Kotlin with suspend only functions (you can run with coroutines if you need async or parallel execution in freeport, Ktor have same HTTPClient strategy). `NftStorageAsync` and `NftStorageSync` will be for java with `CompletableFuture` and blocking calls (`runBlocking`) @upalinski @spoluyan

2021-12-21 08:42 UTC, upalinski commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/client/HttpTransportClient.kt
> +    private fun nextNode() = config.trustedNodes[nodeFlag.getAndIncrement() % config.trustedNodes.size]
AtomicInteger value can become negative on overflow so access by negative index in array will throw an exception and only restart will fix it.

2021-12-21 09:01 UTC, svalasovich commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/client/HttpTransportClient.kt
> +    private fun nextNode() = config.trustedNodes[nodeFlag.getAndIncrement() % config.trustedNodes.size]
Updated

2021-12-21 09:02 UTC, svalasovich commented on build.gradle.kts
> +            "testImplementation"("org.assertj:assertj-core:${Versions.assertj}")
Updated

2021-12-21 09:07 UTC, upalinski commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/NftStorageAsync.kt
> +class NftStorageAsync(private val client: TransportClient) {
@svalasovich is there any need to provide Sync client? 

I would suggest to provide 2 NftStorage's and both of them will be async. The difference will be that coroutine-based client will be in 'kotlin' subpackage.

2021-12-21 09:45 UTC, svalasovich commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/NftStorageAsync.kt
> +class NftStorageAsync(private val client: TransportClient) {
> @svalasovich is there any need to provide Sync client?

Yes, I agree, we don't need. Just followed our agreement in past

2021-12-21 09:51 UTC, svalasovich commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/NftStorageAsync.kt
> +class NftStorageAsync(private val client: TransportClient) {
@upalinski  @spoluyan we can create now only 1 `NftStorage` class for Kotlin with `suspend` and later provide some other module as java extension with required classes for Java using

2021-12-21 10:43 UTC, svalasovich commented on core/src/main/kotlin/network/cere/ddc/core/extension/String.kt
> +fun ByteArray.sha256(): String {
Add dependency for using only sha256 instead Java internal. I am not sure we need it

2021-12-21 10:48 UTC, svalasovich commented on core/src/main/kotlin/network/cere/ddc/core/extension/String.kt
> +fun String.hexToBytes(): ByteArray = Hex.decode(this.removePrefix(HEX_PREFIX))
Updated

2021-12-21 10:48 UTC, svalasovich commented on core/src/main/kotlin/network/cere/ddc/core/extension/String.kt
> +fun ByteArray.toHex(withPrefix: Boolean = true): String {
Removed and used extension khex extension

2021-12-21 10:49 UTC, svalasovich commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/NftStorage.kt
> +        runBlocking { client.storeAsset(nftId, data, name) }
Removed

2021-12-21 10:49 UTC, svalasovich commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/NftStorage.kt
> +        runBlocking { client.readAsset(nftId, nftPath) }
Removed

2021-12-21 10:49 UTC, svalasovich commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/NftStorage.kt
> +        runBlocking { client.storeMetadata(nftId, metadata) }
Removed

2021-12-21 10:49 UTC, svalasovich commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/NftStorage.kt
> +        runBlocking { client.readMetadata(nftId, nftPath, schema) }
Removed

2021-12-21 11:12 UTC, svalasovich commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/client/HttpTransportClient.kt
> +    private val objectMapper = jacksonObjectMapper()
Yes, but in our case we don't have blocking operation, it's false positive warning. https://github.com/FasterXML/jackson-module-kotlin/issues/313#issuecomment-874271261

2021-12-21 11:53 UTC, svalasovich commented on core/src/main/kotlin/network/cere/ddc/core/signature/Scheme.kt
> +        const val ETHEREUM = "ethereum"
Updated

2021-12-23 14:46 UTC, svalasovich commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/client/HttpTransportClient.kt
> +    override suspend fun readMetadata(nftId: String, nftPath: NftPath): ObjectNode {
I decided to return Jackson's ObjectNode, because response doesn't have static schema and can be in any schema JSON type. Generic will force user to know schema before request.

2021-12-23 23:28 UTC, svalasovich commented on build.gradle.kts
> +            "testImplementation"("com.github.tomakehurst:wiremock:${Versions.wiremock}")
Removed

2021-12-24 07:44 UTC, upalinski commented on core/src/main/kotlin/network/cere/ddc/core/extension/Common.kt
> +    for (i in 1 until times) {
repeat(times) {
}

2021-12-24 07:50 UTC, upalinski commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/NftStorage.kt
> +class NftStorage(private val client: TransportClient, private val config: NftStorageConfig = NftStorageConfig()) {
let's add default value for transport?

2021-12-24 07:56 UTC, upalinski commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/config/TransportClientConfig.kt
> +    val retryTimes: Int = 3,
do you need retries configuration in both NftStorageConfig and TransportClientConfig?

2021-12-24 07:56 UTC, upalinski commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/exception/AssetReadNftException.kt
> +class AssetReadNftException(message: String, cause: Throwable) : NftException(message, cause)
Do we really need separate exception class for each operation?

2021-12-24 08:01 UTC, upalinski approved these changes

2021-12-24 08:13 UTC, svalasovich commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/NftStorage.kt
> +class NftStorage(private val client: TransportClient, private val config: NftStorageConfig = NftStorageConfig()) {
I think it's impossible, we need to know list of nodes for connection... I can suggest create NftStorageFactory class for creating default NftStorage by only 1 parameter (list nodes) and default other (Scheme, configs) @upalinski

2021-12-24 08:15 UTC, svalasovich commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/config/TransportClientConfig.kt
> +    val retryTimes: Int = 3,
Yes, It's for flexibility. TransportClientConfig retry gives possibility configure how many requests to 1 node, NftStorageConfig gives configure how many retries to different nodes

2021-12-24 08:28 UTC, svalasovich commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/exception/AssetReadNftException.kt
> +class AssetReadNftException(message: String, cause: Throwable) : NftException(message, cause)
For our case no, but I think it will not be superfluous for catching some specific fails.

2021-12-24 08:29 UTC, svalasovich commented on core/src/main/kotlin/network/cere/ddc/core/extension/Common.kt
> +    for (i in 1 until times) {
Updated

2021-12-27 13:26 UTC, vadim-hleif requested changes

2021-12-27 13:26 UTC, vadim-hleif commented on core/src/main/kotlin/network/cere/ddc/core/http/HttpSecurity.kt
> +                    ZonedDateTime.now().plus(feature.expiresAfter).format(DateTimeFormatter.RFC_1123_DATE_TIME)
why do you use zoned date? as I understand this header is sent to ddc, but ddc can use another time zone (am I right?)

2021-12-27 13:26 UTC, vadim-hleif commented on core/src/main/kotlin/network/cere/ddc/core/http/HttpSecurity.kt
> +class HttpSecurity {
docs what's going on there

2021-12-27 13:26 UTC, vadim-hleif commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/NftStorage.kt
> +    suspend fun storeAsset(nftId: String, data: ByteArray, name: String): NftPath = try {
docs (the same what I've mentioned in README)

2021-12-27 13:26 UTC, vadim-hleif commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/model/Edek.kt
> +    @field: JsonProperty("publicKey")
why did you mark all fields all nullable? in all models

Is it so?

2021-12-27 13:31 UTC, svalasovich commented on core/src/main/kotlin/network/cere/ddc/core/http/HttpSecurity.kt
> +                    ZonedDateTime.now().plus(feature.expiresAfter).format(DateTimeFormatter.RFC_1123_DATE_TIME)
Yes, that's why we need to add timezone, so DDC node could check if time expired with different timezones on client and ddc node + RFC_1123_DATE_TIME require timezone

2021-12-27 13:33 UTC, svalasovich commented on nft-storage/src/main/kotlin/network/cere/ddc/nft/model/Edek.kt
> +    @field: JsonProperty("publicKey")
It's for native compilation Quarkus GraalVM. I know It's ugly to work nullable field when it's not null, but it requirements of correct native work

2021-12-27 13:41 UTC, svalasovich commented on README.md
> +    Node(id = "12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT", address = "https://127.0.0.1:8080"),
We tries to make request safe and impossible redirect to other node. If to be short some nodes can be unscrupulous and redirect all work to other cheeper node, we tries to avoid this by adding NodeId and sign request with nodes `HttpSecurity` plugin adds headers

2021-12-27 13:46 UTC, svalasovich commented on core/src/main/kotlin/network/cere/ddc/core/http/HttpSecurity.kt
> +class HttpSecurity {
I think it's more internal structure component, not for README or general using.  I can add comments for class

2021-12-27 13:57 UTC, svalasovich commented on README.md
> +    Node(id = "12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT", address = "https://127.0.0.1:8080"),
At first sight it will be difficult get NodeId for users, but I think It have same difficult as get HTTP address

2021-12-27 13:58 UTC, svalasovich commented on README.md
> +val metadata = Erc721Metadata(
It's NFT standard [NFT metadata](https://nftschool.dev/reference/metadata-schemas/#intro-to-json-schemas) I am not sure if we need it to add, because it's more basic standard, just very short description may be.

2021-12-27 14:22 UTC, vadim-hleif commented on core/src/main/kotlin/network/cere/ddc/core/http/HttpSecurity.kt
> +class HttpSecurity {
yes, I meant java docs

I don't know who can commit in this repo, I just imagined that Freeport team also can and without docs it can be painful.

2021-12-27 16:03 UTC, vadim-hleif approved these changes

2021-12-28 07:21 UTC, merged